/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante;

import javax.swing.JOptionPane;

/**
 *
 * @author SCIS2-19
 */
public class Menu extends javax.swing.JFrame {

    int [][] menu;
    String[] platosNuevos;
    String[] dias;
    int cantPlatos;
    int cantDias;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IngresarPlatos = new javax.swing.JButton();
        mostrarMenu = new javax.swing.JButton();
        ingresarVentas = new javax.swing.JButton();
        calcularVentas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Restaurante");

        IngresarPlatos.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        IngresarPlatos.setText("Ingresar Platos");
        IngresarPlatos.setBorder(null);
        IngresarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarPlatosActionPerformed(evt);
            }
        });

        mostrarMenu.setText("Mostrar Menu");
        mostrarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarMenuActionPerformed(evt);
            }
        });

        ingresarVentas.setText("Ingresar Ventas");
        ingresarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarVentasActionPerformed(evt);
            }
        });

        calcularVentas.setText("Calcular Ventas");
        calcularVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(147, 147, 147))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IngresarPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarVentas))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calcularVentas)
                    .addComponent(mostrarMenu))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarMenu))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarVentas)
                    .addComponent(calcularVentas))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarPlatosActionPerformed
        // TODO add your handling code here:
        //int cm = Integer.parseInt(JOptionPane.showInputDialog("Columna a Modificar").trim());

        try{
            cantPlatos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de platos").trim());
            cantDias = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de dias que trabaja").trim());
            
            //Saber qué dias trabaja / No funciona
            //String []diasTrabajados = ["lunes", "martes"];
            platosNuevos = new String[cantPlatos];
            dias = new String[cantDias];
            
            for(int i = 0; i<cantDias; i++){
                String b = JOptionPane.showInputDialog("Ingrese los dias de trabajo, ejemplo:Lunes").trim();
                dias[i] = b;
            }
            for(int i = 0; i<cantPlatos; i++){
                String a = JOptionPane.showInputDialog("Ingrese los platos").trim();
                platosNuevos[i] = a;
            }
            menu = new int[dias.length][platosNuevos.length];

            for(int i = 0; i<dias.length; i++){
                for(int j = 0; j<platosNuevos.length; j++){
                }
            }
            
            
            
        }catch(Exception err){
            JOptionPane.showMessageDialog(null, err);
        }
    }//GEN-LAST:event_IngresarPlatosActionPerformed

    private void mostrarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarMenuActionPerformed
        // TODO add your handling code here:
        //if(menu == null){
           // JOptionPane.showMessageDialog(null,"No hay datos");
        //}else{
        try{
            if(platosNuevos==null){
            JOptionPane.showMessageDialog(null, "No hay datos");

            }else{
                for(int j = 0; j<platosNuevos.length; j++){
                    System.out.println(platosNuevos[j]);
                //        JOptionPane.showMessageDialog(null, platosNuevos);
                }
            }
        }catch(Exception err){
            System.out.println(err);
        }
        //}
    }//GEN-LAST:event_mostrarMenuActionPerformed

    private void ingresarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarVentasActionPerformed
        // TODO add your handling code here:
         try{
            if(platosNuevos==null || dias==null){
            JOptionPane.showMessageDialog(null, "No hay datos");

            }else{
                menu = new int[dias.length][platosNuevos.length]; 
                for(int i = 0; i<dias.length; i++){
                    for(int j = 0; j<platosNuevos.length; j++){
                    //        JOptionPane.showMessageDialog(null, platosNuevos);
                    
                    int b = Integer.parseInt(JOptionPane.showInputDialog("Ingrese ventas el día: "+dias[i]+ " para el plato: "+platosNuevos[j]).trim());
                    menu[i][j] = b;
                    }
                }
            }
        }catch(Exception err){
            System.out.println(err);
        }
    }//GEN-LAST:event_ingresarVentasActionPerformed

    private void calcularVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularVentasActionPerformed
        // TODO add your handling code here:
        try{
            if(menu == null){
            JOptionPane.showMessageDialog(null, "No hay datos");

            }else{
                menu = new int[dias.length][platosNuevos.length]; 
                int[] totalVentasPorDia = new int[dias.length];
                int ventaMayor;
                int suma = 0;
                
                for(int i = 0; i<dias.length; i++){
                    suma = 0;
                    for(int j = 0; j<platosNuevos.length; j++){
                        suma += menu[i][j];
                    }
                    totalVentasPorDia[i] = suma;
                }
                int diaMax = 0;
                int diaMin = 0;
                
                for (int i = 1; i < totalVentasPorDia.length; i++) {
                    if (totalVentasPorDia[i] > totalVentasPorDia[diaMax]) {
                        diaMax = i;
                    }
                    if (totalVentasPorDia[i] < totalVentasPorDia[diaMin]) {
                        diaMin = i;
                    }
                }
                System.out.println("Dia más vendido: "+dias[diaMax]);
            }
        }catch(Exception err){
            System.out.println(err);
        }
    }//GEN-LAST:event_calcularVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarPlatos;
    private javax.swing.JButton calcularVentas;
    private javax.swing.JButton ingresarVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mostrarMenu;
    // End of variables declaration//GEN-END:variables
}
